<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="manish-PC" name="Firefox Test" tests="2" failures="2" timestamp="18 Jul 2017 03:39:13 GMT" time="64.54" errors="0">
  <testcase name="@AfterTest closeBrowser" time="0.0" classname="com.testng.exmple.ParallelExp2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.testng.exmple.ParallelExp2.closeBrowser(ParallelExp2.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- @AfterTest closeBrowser -->
  <testcase name="login_TestCase" time="0.014" classname="com.testng.exmple.ParallelExp2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.testng.exmple.ParallelExp2.login_TestCase(ParallelExp2.java:40)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- login_TestCase -->
  <testcase name="search_TestCase" time="0.002" classname="com.testng.exmple.ParallelExp2">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.testng.exmple.ParallelExp2.search_TestCase(ParallelExp2.java:46)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- search_TestCase -->
</testsuite> <!-- Firefox Test -->
